{
  "unversionedId": "metaflow/failures",
  "id": "metaflow/failures",
  "title": "Dealing with Failures",
  "description": "Failures are a natural, expected part of data science workflows. Here are some typical reasons why you can expect your workflow to fail:",
  "source": "@site/docs/metaflow/failures.md",
  "sourceDirName": "metaflow",
  "slug": "/metaflow/failures",
  "permalink": "/docusaurus/docs/metaflow/failures",
  "editUrl": "https://github.com/outerbounds/docusaurus/tree/main/docs/metaflow/failures.md",
  "tags": [],
  "version": "current",
  "frontMatter": {},
  "sidebar": "python",
  "previous": {
    "title": "Managing External Libraries",
    "permalink": "/docusaurus/docs/metaflow/dependencies"
  },
  "next": {
    "title": "Organizing Results",
    "permalink": "/docusaurus/docs/metaflow/tagging"
  }
}